---
galaxy_info:
  author: homelab
  description: WireGuard Manager service with Telegram bot
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []
