---
collections:
  - name: community.docker
    version: ">=3.0.0"
  - name: prometheus.prometheus
    version: ">=0.16.0"
  - name: community.general
    version: ">=8.0.0"

roles:
  - name: geerlingguy.docker
    version: "8.0.0"
